# Nombre representativo para el workflow
name: Hola Mundo

# Eventos. Cuándo se va a ejecutar. En este caso se ejecuta al hacer push al repo.
on: [push]

# Jobs. Permiten ejecutar todo lo que se necesite dentro de un servidor, actions provee varios servidores: ubuntu, windows y mac
# Para especificar SO usamos la directiva runs-on
# Steps. Unidad más pequeña que eprmite realizar diferentes acciones
# Acción. Hay varias directivas: run, que permite ejecutar comando
# Jobs se ejecutan independientes, pero de forma paralela, entonces van haber ocasiones en las que encesitamos que un job se 
# ejecute después de otro job. Para ahcerlo usamos la directiva needs
jobs:
  hola:
    runs-on: ubuntu-latest

    steps:
    - name: Hola Mundo
      run: echo "Hola Mundo"
    
    - name: touch file
      run: touch hola.txt
    
    - name: Set text
      run: echo "Hola Mundo" >> hola.txt
    
    - name: Read file 
      run: cat hola.txt


# Dentro de un workflow puedes tener múltiples jobs. Y cada uno se ejecuta en un servidor, entonces es necesario declarar runs-on en cada job
  other:
    runs-on: ubuntu-latest
    needs: [hola]
    steps:
    - name: LS
      run: ls -al


